### ISSUE TITLE
What is the API rate limit?

### ISSUE THREAD

**Issue by artemave** [browserstack/api#31]
I am getting this rate limit error (tests are using the latest karma-browserstack-launcher):

```
21 12 2018 17:32:40.723:INFO [launcher.browserstack]: Firefox (OS X Mojave) session at https://automate.browserstack.com/builds/1edbceee868d11599f454db274b4e1c7fa2908fe/sessions/d84ec96b49fc2f1ab33be6ff0e1f6df6caa8784b
Error: 403 Forbidden (Rate Limit Exceeded)

    at IncomingMessage.<anonymous> (/home/circleci/repo/node_modules/browserstack/lib/client.js:74:8)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Step was canceled
```

Thank you!

**Comment by swapnilagarwwal** [comment]
Hi @artemave 
How many requests are you making?
Please refer https://www.browserstack.com/automate/rest-api#rest-api-projects
You can make up to 800 API requests per 5 minutes per user.

**Comment by artemave** [comment]
Thank you!
